#!/bin/bash

declare -A EMOJI_MAP=(
	[inbox]="📥"
	[art]="🎨"
	[dibujos]="🎨"
	[arte]="🎨"
	[draws]="🎨"
	[money]="💰"
	[dinero]="💰"
	[health]="🏋️‍♂️"
	[projects]="🛠️"
	[archive]="🗄️"
	[pics]="🏞️"
	[photos]="🏞️"
	[fotos]="🏞️"
	[videos]="🎞️"
	[music]="🎵"
	[música]="🎵"
	[docs]="📄"
	[trash]="🗑️"
	[courses]="👨‍🏫"
	[diamond]="💎"
	[notes]="🗒️"
	[shell]="🐚"
	[apple]="🍎"
	[web]="🕸️"
	[bear]="🐻‍❄️"
	[pen]="🖋️"
	[writing]="🖋️"
	[pro]="💼"
	[work]="💼"
	[pray]="🙏"
	[prayer]="🙏"
	[prayers]="🙏"
	[religion]="🙏"
	[rezar]="🙏"
	[orar]="🙏"
	[oración]="🙏"
	[links]="🔗"
	[enlaces]="🔗"
	[references]="🔗"
	[ideas]="💡"
	[drop]="💧"
	[dev]="💻"
	[macbook]="💻"
	[shell]="🐚"
	[scripting]="🐍"
	[testing]="✅"
	[network]="🌐"
	[networking]="🌐"
	[ui]="🎨"
	[architecture]="🏛️"
	[politics]="🏛️"
	[pol]="🏛️"
	[explorations]="👨🏻‍🔬"
	[experiments]="👨🏻‍🔬"
	[grounds]="👨🏻‍🔬"
	[concurrency]="🔀"
	[misc]="🧐"
	[brain]="🧠"
	[memory]="🧠"
	[memory-management]="🧠"
	[puzzle]="🧩"
	[snippets]="🧩"
	[design-patterns]="🧩"
	[top]="🎖️"
	[medal]="🎖️"
	[math]="🧮"
	[abacus]="🧮"
	[algos]="🧮"
	[algo]="🧮"
	[algoritmos]="🧮"
	[alogrhythm]="🧮"
	[folder]="🗂️"
	[documents]="🗂️"
	[docs]="🗂️"
	[notes]="🗒️"
	[violin]="🎻"
	[guitar]="🎸"
	[music]="🎵"
)

::() {
	local key="$1"
	local emoji="${EMOJI_MAP[$key]}"

	if [[ -z "$emoji" ]]; then
		echo "❌ Unknown key: $key"
		return 1
	fi

	cd "$emoji" || echo "❌ Could not cd into $HOME/$emoji"
}
