source ~/dotfiles/setup.sh

export BUN_INSTALL="$HOME/.bun"
export PNPM_HOME="$HOME/Library/pnpm"
path "/bin"
path "/usr/bin"
path "/usr/local/bin"
path "/usr/local/opt/ruby/bin"
path "/usr/local/lib/ruby/gems/2.7.0/bin"
path "/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin"
path "/opt/homebrew/bin"
path "$BUN_INSTALL/bin"
path "/opt/homebrew/opt/openjdk/bin"
path "$PNPM_HOME"
path "$HOME/.config/emacs/bin"
path "$HOME/.local/bin"
path "$HOME/.nimble/bin"

path_end "$HOME/.composer/vendor/bin"
path_end "/usr/local/go/bin"
