source ~/dotfiles/modules/vcs.sh
source ~/dotfiles/modules/brew-config.sh
source ~/dotfiles/modules/misc.sh
source ~/dotfiles/modules/emoji-mapper.sh
source ~/dotfiles/modules/uninstall.sh
source ~/dotfiles/modules/apppath.sh
source ~/dotfiles/modules/cat.sh
source ~/dotfiles/modules/rm.sh
source ~/dotfiles/modules/merge.sh
